### ISSUE TITLE
Supporting the Mimas A7 FPGA board

### ISSUE THREAD

**Issue by gardners** [cambridgehackers/fpgajtag#4]
Hello again,

Now I am trying to extend fpgajtag so that it works with a new FPGA board I bought, that seems to have a different pinout on the FTDI side of things, the Mimas A7.

First step, the device uses a different vendor and product id, which was easy enough to patch in util.c with something like:
```

        if (
	    // FTDI-based boards from Trenz, Digilent etc
	    ( desc.idVendor == 0x403 && (desc.idProduct == 0x6001 || desc.idProduct == 0x6010
					 || desc.idProduct == 0x6011 || desc.idProduct == 0x6014))
	    ||
	    // Mimas A7 and similar boards
	    ( desc.idVendor == 0x2a19 && (desc.idProduct == 0x1009 ))
	    )
	  { /* Xilinx */

```
With that in place, I can find the USB device, but thte JTAG boundary scan indicates IDs of all zero. This is caused by the funny FTDI JTAG pinout they are using, as far as I can tell.
Fortunately, there is an OpenOCD config file that explains the setup required for that:

https://numato.com/kb/programming-mimas-a7-using-openocd-and-xc3sprog/

And this page from Numato has the FTDI pinouts:

https://numato.com/docs/mimas-artix-7-fpga-development-board-with-ddr-sdram-and-gigabit-ethernet/

My guess is that we need to rearrange the bits in the bytes when read/written to the FTDI.

Mimas A7 schematic from https://numato.com/docs/mimas-artix-7-fpga-development-board-with-ddr-sdram-and-gigabit-ethernet/ indicates that the JTAG pins on the FTDI are:

BDBUS0 = TCK
BDBUS1 = TDI
BDBUS2 = TDO
BDBUS3 = TMS

While on the TE0790 JTAG programming adapter that does work with fpgajtag, they are on:

ADBUS0 = TCK
ADBUS1 = TDI
ADBUS2 = TDO
ADBUS3 = TMS

So we don't need to fiddle bits -- just change the FTDI commands to work on the BDBUS instead of the ADBUS.... however that works.  Currently trying to figure that part out...

**Comment by gardners** [comment]
Digging into FT2232H datasheet at: https://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT2232H.pdf

It looks like we might just need to change which interface # we talk to.
Setting interface=1 in fpgajtag.c instead of the default (implied) interface=0 certainly causes different behavjour: It de-configures the FPGA and the JTAG boundary scan now returns all 0xFFFFFFFFs instead of all 0s. So something is still clearly a bit wrong.

We also need to make sure we set bit 6 to output, as this is the output enable, and keep bit 7 as input, as this is the PROG line on the FPGA.

By doing that, I can now correctly read the JTAG IDs, and with a bit more hacking, I am able to attempt to push bitstreams, but I am getting some errors still, and it doesn't actually program the FPGA:

```
Found matching device.
count 0/1 cortex -1 dcount 0 trail 0
STATUS 00400019 done 0 release_done 0 eos 10 startup_state 0
[fpgajtag_main:912] NOOP/INPROGRAMMING mismatch fc
fpgajtag: Starting to send file
fpgajtag: Done sending file
[fpgajtag_main:927] CONFIG_REG_BOOTSTS mismatch ffffffff
[fpgajtag_main:931] mismatch fc
fpgajtag: bypass unknown fc
```

(This is actually using the MEGA65 monitor_load command that includes fpgajtag in it. Will provide a patch summary.)

This suggests that I am still driving some line wrong or something.

**Comment by gardners** [comment]
Just confirmed that openocd CAN correctly load a bitstream, using a command like this:

sudo openocd -f ~/Downloads/mimasa7-openocd.cfg -c "init" -c "pld load 0 ../Minimig_ECS/bin/mimasa7.bit" -c "shutdown"

So it IS possible, and just a case of figuring out what else is wrong.

Any suggestions for lines of enquiry most welcome.

**Comment by jameyhicks** [comment]
It sounds like you are making good progress! I found usbmon to be helpful to see how a particular USB protocol works.
   https://www.kernel.org/doc/Documentation/usb/usbmon.txt

It might help you find what the missing pieces are.

**Comment by jankcorn** [comment]
Hi,

I am looking at the OCD cfg files to backtrack necessary changes:
   https://github.com/ntfreak/openocd/blob/master/tcl/board/numato_mimas_a7.cfg
and
   https://github.com/ntfreak/openocd/blob/master/tcl/interface/ftdi/digilent_jtag_smt2.cfg
   (I am most accustomed to using the zedboard)

Do you have a scope you can attach to the mimas jtag pins, just to see
if they are wiggling in roughly the right pattern for jtag?
Also, you might need to lower the serial clocking freq in util.c.  I
have noticed that some xilinx boards have the traces poorly terminated
and require that the clock frequency be reduced to prevent ringing.

I will look more into the cfg differences tomorrow morning, to locate
where these are reflected in the util.c source.

**Comment by jankcorn** [comment]
Comparing the cfg files, it looks like there is a small difference in
params to SET_BITS_LOW/SET_BITS_HIGH.
I have added/pushed a couple of (untested!) changes; would you be
willing to try them?

Changes:
    1. Added '-d MIMAS_A7' command line parameter to specify device type
    2. Added your suggested change for USB ID
    3.  added a change to fpgajtag.c/init_device() to use the values
seen in OCD cfg files

Note: I have not lowered the clock frequency (set in fpgausb_open with
'best_divisor').

Hope this works!
jca

**Comment by gardners** [comment]
Confirmed it compiles on Ubuntu, but generates segmentation faults ("Speicherzugriffsfehler" in the following, computer is set to German).

```
paul@F96NG92-L:~/Projects/mega65/fpgajtag$ make clean
make -C src clean
make[1]: Verzeichnis „/home/paul/Projects/mega65/fpgajtag/src“ wird betreten
rm -rf fpgajtag.o process.o cortex.o util.o fpgajtag.a fpgajtag obj libs
make[1]: Verzeichnis „/home/paul/Projects/mega65/fpgajtag/src“ wird verlassen
paul@F96NG92-L:~/Projects/mega65/fpgajtag$ make
make -C src
make[1]: Verzeichnis „/home/paul/Projects/mega65/fpgajtag/src“ wird betreten
cc  -Wall -fPIC -I/usr/include/libusb-1.0 -I/opt/local/include/libusb-1.0 -I/usr/local//Cellar/libusb/1.0.18/include/libusb-1.0/ -g   -c -o fpgajtag.o fpgajtag.c
cc  -Wall -fPIC -I/usr/include/libusb-1.0 -I/opt/local/include/libusb-1.0 -I/usr/local//Cellar/libusb/1.0.18/include/libusb-1.0/ -g   -c -o process.o process.c
cc  -Wall -fPIC -I/usr/include/libusb-1.0 -I/opt/local/include/libusb-1.0 -I/usr/local//Cellar/libusb/1.0.18/include/libusb-1.0/ -g   -c -o cortex.o cortex.c
cc  -Wall -fPIC -I/usr/include/libusb-1.0 -I/opt/local/include/libusb-1.0 -I/usr/local//Cellar/libusb/1.0.18/include/libusb-1.0/ -g   -c -o util.o util.c
rm -f fpgajtag.a
ar -cr fpgajtag.a fpgajtag.o process.o cortex.o util.o
gcc -g -o fpgajtag main.c fpgajtag.a -lpthread  -lusb-1.0 -lz
make[1]: Verzeichnis „/home/paul/Projects/mega65/fpgajtag/src“ wird verlassen
paul@F96NG92-L:~/Projects/mega65/fpgajtag$ sudo src/fpgajtag -l
count -1/0 cortex -1 dcount -1 trail 0
Speicherzugriffsfehler
paul@F96NG92-L:~/Projects/mega65/fpgajtag$ sudo src/fpgajtag -d MIMAS_A7 -l
fpgajtag: Numato Lab:Mimas Artix 7 FPGA Module:NL4IT7JQ; bcd:700; IDCODE:  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
count -1/16 cortex -1 dcount 15 trail 16
Speicherzugriffsfehler
paul@F96NG92-L:~/Projects/mega65/fpgajtag$ 
```

Cause seems to be usbhandle is null:

```
Reading symbols from src/fpgajtag...fertig.
(gdb) set args -l
(gdb) run
Starting program: /home/paul/Projects/mega65/fpgajtag/src/fpgajtag -l
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6f69700 (LWP 19752)]
count -1/0 cortex -1 dcount -1 trail 0

Thread 1 "fpgajtag" received signal SIGSEGV, Segmentation fault.
0x00007ffff79a8c21 in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
(gdb) up
#1  0x00007ffff79a903f in libusb_bulk_transfer () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
(gdb) up
#2  0x0000555555559862 in ftdi_write_data (ftdi=0x0, buf=0x555561621460 <usbreadbuffer> "K", <incomplete sequence \347>, size=3)
    at util.c:139
139	    ret = libusb_bulk_transfer(usbhandle, ENDPOINT_IN, (unsigned char *)buf, size, &actual_length, USB_TIMEOUT);
(gdb) print buf
$1 = (const unsigned char *) 0x555561621460 <usbreadbuffer> "K", <incomplete sequence \347>
(gdb) print size
$2 = 3
(gdb) print actual_length
$3 = -1
(gdb) print usbhandle
$4 = (libusb_device_handle *) 0x0
(gdb) 
```

**Comment by gardners** [comment]
Segfault was actually introduced with this commit:

9cf9a310d5397e386e6485ec1fc3fdf643b2e16a

Paul.

**Comment by gardners** [comment]
Apart from that, I would just make the observation that this USB vend:prod tuple should only ever show up for the MIMAS board, so it can probably be made the default for that, once we have confirmed it working.

**Comment by jankcorn** [comment]
I updated the source to correctly handle error returns when
initializing the device, so your segv should go away.
Note that the core problem, reading all '0', remains...
I am having a separate USB issue in my test environment here (on my
Mac), so am rebuilding a linux box for verification.   Will let you
know how this goes.
jca

**Comment by gardners** [comment]
Ok, that fixes the segfault, but now it doesn't see the device when I ask for a list:
```

[1923298.758392] usb 1-4: new high-speed USB device number 62 using xhci_hcd
[1923298.911415] usb 1-4: New USB device found, idVendor=2a19, idProduct=1009
[1923298.911417] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[1923298.911418] usb 1-4: Product: Mimas Artix 7 FPGA Module
[1923298.911419] usb 1-4: Manufacturer: Numato Lab
[1923298.911419] usb 1-4: SerialNumber: NL4IT7JQ
[1923298.914700] ftdi_sio 1-4:1.0: FTDI USB Serial Device converter detected
[1923298.914738] usb 1-4: Detected FT2232H
[1923298.914902] usb 1-4: FTDI USB Serial Device converter now attached to ttyUSB0
[1923298.917447] ftdi_sio 1-4:1.1: FTDI USB Serial Device converter detected
[1923298.917483] usb 1-4: Detected FT2232H
[1923298.917748] usb 1-4: FTDI USB Serial Device converter now attached to ttyUSB2
paul@F96NG92-L:~/Projects/mega65/fpgajtag$ sudo src/fpgajtag -l
paul@F96NG92-L:~/Projects/mega65/fpgajtag$ 
```

**Comment by jankcorn** [comment]
I see now how you are expecting to use this!

I originally coded it so that the device type must be given as a
command line parameter.

I have added/pushed code so that it will be auto set with 2a19/1009 is detected.

**Comment by gardners** [comment]
ok, that lets me get a bit further again:

```
$ sudo src/fpgajtag -l
[sudo] Passwort für paul: 
fpgajtag: Numato Lab:Mimas Artix 7 FPGA Module:NL4IT7JQ; bcd:700; IDCODE:  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
```

But still the all 0's.  This suggests to me that the bit setup stuff is still wrong, as I was able to get past this in my fork in the mega65-core repo  in src/tools/fpgajtag.

Paul

**Comment by gardners** [comment]
See, e.g., 

https://github.com/MEGA65/mega65-core/commit/1b24c59bc70333d12a117424b50e3e34fcad2df1

**Comment by jankcorn** [comment]
Can you send the dump of Idcode from running your branch?
I’ll look into it tomorrow morning.
Tx

**Comment by jankcorn** [comment]
I pushed the changes from your branch.  Are you able to program the Artix?

**Comment by gardners** [comment]
ok, so now I can see the FPGA ID:

```
$ sudo src/fpgajtag -l
[sudo] Passwort für paul: 
fpgajtag: Numato Lab:Mimas Artix 7 FPGA Module:NL4IT7JQ; bcd:700; IDCODE:  362c093
$
```

You are now as far along as I managed to get:

```
$ sudo src/fpgajtag  ../Minimig_ECS/bin/mimasa7-.bit 
fpgajtag: Numato Lab:Mimas Artix 7 FPGA Module:NL4IT7JQ; bcd:700
count 0/1 cortex -1 dcount 0 trail 0
STATUS 00401079 done 0 release_done 0 eos 10 startup_state 0
[fpgajtag_main:813] NOOP/INPROGRAMMING mismatch fc
fpgajtag: Starting to send file
fpgajtag: Done sending file
[fpgajtag_main:828] CONFIG_REG_BOOTSTS mismatch ffffffff
[fpgajtag_main:832] mismatch fc
fpgajtag: bypass unknown fc
STATUS 00ffffff done 4000 release_done 2000 eos 10 startup_state 7
fpgajtag: ERROR failed to run pciescanportal: No such file or directory
paul@F96NG92-L:~/Projects/mega65/fpgajtag$
```

It deconfigures the FPGA, but doesn't succeed in reconfiguring it (the DONE signal never occurs).
I have no idea what is the problem here. This might require me to run usbmon and compare what OpenOCD does.  My gut feeling is that it will be something simple, since we get the correct JTAG ID from the chip.

**Comment by jankcorn** [comment]
Since it seems like it might (possibly) be having problems with the
bitfile, could you try reversing the byte order and attempt to program
again.

The tool I want you to use is in the repo:
     https://github.com/cambridgehackers/connectal
as:
     scripts/reorderbytes.py

For example:
     scripts/reorderbytes.py input_file output_file
then
    fpgajtag output_file

We have had byte order problems in the past when programming the Zynq
fpga through the onboard linux driver from the Cortex processor, so I
don't think this is relevant for you, but just in case....

Also.... I added/pushed some example code for lowering the clock freq,
in case that is an issue (grep for the variable 'clock_frequency' in
the source).  Looking at numato_mimas_a7.cfg, it would appear that
30MHz (my default) should be fine, but YMMV.

If I can think of any other things to try, I'll email.

**Comment by gardners** [comment]
That conversion doesn't work for some reason, barfing on the standard header of the .BIT file.
Have I done something wrong here? 

```
$ scripts/reorderbytes.py orig.bit reorder.bit
Traceback (most recent call last):
  File "scripts/reorderbytes.py", line 36, in <module>
    readarr = array.array('I', infile.read())
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 3: invalid continuation byte
paul@F96NG92-L:~/Projects/mega65/connectal$ hexdump -C orig.bit | head -20
00000000  00 09 0f f0 0f f0 0f f0  0f f0 00 00 01 61 00 39  |.............a.9|
00000010  63 6f 6e 74 61 69 6e 65  72 3b 55 73 65 72 49 44  |container;UserID|
00000020  3d 30 58 46 46 46 46 46  46 46 46 3b 43 4f 4d 50  |=0XFFFFFFFF;COMP|
00000030  52 45 53 53 3d 54 52 55  45 3b 56 65 72 73 69 6f  |RESS=TRUE;Versio|
00000040  6e 3d 32 30 31 37 2e 34  00 62 00 0c 37 61 35 30  |n=2017.4.b..7a50|
00000050  74 66 67 67 34 38 34 00  63 00 0b 32 30 32 30 2f  |tfgg484.c..2020/|
00000060  30 34 2f 32 39 00 64 00  09 31 31 3a 30 38 3a 33  |04/29.d..11:08:3|
00000070  35 00 65 00 07 df cc ff  ff ff ff ff ff ff ff ff  |5.e.............|
00000080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00000190  ff ff ff ff ff ff ff 00  00 00 bb 11 22 00 44 ff  |............".D.|
000001a0  ff ff ff ff ff ff ff aa  99 55 66 20 00 00 00 30  |.........Uf ...0|
000001b0  03 e0 01 00 00 02 6c 30  00 80 01 00 00 00 12 20  |......l0....... |
000001c0  00 00 00 30 02 20 01 00  00 00 00 30 02 00 01 00  |...0. .....0....|
000001d0  00 00 00 30 00 80 01 00  00 00 00 20 00 00 00 30  |...0....... ...0|
000001e0  00 80 01 00 00 00 07 20  00 00 00 20 00 00 00 30  |....... ... ...0|
000001f0  02 60 01 00 00 00 00 30  01 20 01 02 30 3f e5 30  |.`.....0. ..0?.0|
00000200  01 c0 01 00 00 00 00 30  01 80 01 03 62 c0 93 30  |.......0....b..0|
00000210  00 80 01 00 00 00 09 20  00 00 00 30 00 c0 01 00  |....... ...0....|
00000220  00 04 01 30 00 a0 01 00  00 05 01 30 00 c0 01 00  |...0.......0....|

```

The speed reduction alone also didn't fix the problem:

```
$ sudo src/fpgajtag ../connectal/orig.bit 
fpgajtag: Numato Lab:Mimas Artix 7 FPGA Module:NL4IT7JQ; bcd:700
count 0/1 cortex -1 dcount 0 trail 0
STATUS 00401079 done 0 release_done 0 eos 10 startup_state 0
[fpgajtag_main:818] NOOP/INPROGRAMMING mismatch fc
fpgajtag: Starting to send file
fpgajtag: Done sending file
[fpgajtag_main:833] CONFIG_REG_BOOTSTS mismatch ffffffff
[fpgajtag_main:837] mismatch fc
fpgajtag: bypass unknown fc
STATUS 00ffffff done 4000 release_done 2000 eos 10 startup_state 7
fpgajtag: ERROR failed to run pciescanportal: No such file or directory
```

**Comment by jankcorn** [comment]
The python problem is truly bizarre.  The reorderbytes.py file does an
'import array', but somehow ends up calling codec.py?  How strange.
In addition, the python library doc for array.array does not mention
unicode for 'I'.
I will leave this as a 'mystery of the universe'.

I think that I _may_ have located the problem...  there was digilent
jtag interface-specific GPIO code that was still being invoked in the
current version.  The effect of this will be to mess up the OE and
PROGRAM_B lines going to the A7.
I edited/pushed a change for this.  (although, I am not sure whether
the PROGRAM_B line needs to be pulled up after configuration)

For reference (but no need to look at these):
    https://numato.com/help/wp-content/uploads/2018/06/MimasA7_V3.1_Sch.pdf
         Page 8, pins BDBUS6 (OE) and BDBUS7 (PROGRAM_B, going to inverter)
    https://www.xilinx.com/support/documentation/user_guides/ug470_7Series_Config.pdf
         Page 25, describes operation of PROGRAM_B

Hope this works!

**Comment by gardners** [comment]
Yes, that fixed the problem! Thanks for helping with this.

**Comment by gardners** [comment]
(Is it worth making those extra steps only happen if the board is a digilent one, instead of when it isn't a MIMAS board, perhaps?)

**Comment by jankcorn** [comment]
In general, seems reasonable.  Strangely, all the Xilinx dev boards we
have tried, use one of the Digilent USB interfaces (including Kintex
and Virtex).

I should probably just break down and make a config file, so that all
boards are just listed eplicitly.

For now, glad to hear that it works!
Thanks for hanging in there.

**Comment by jankcorn** [comment]
In future, support config file for USB VID/PID, GPIO usage and SET_LOW/HIGH_BITS values
